name: freq_fit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


# my dependancies
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.7.0
  sound_generator: ^0.0.9
  headset_connection_event: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Black.ttf
        - asset: assets/fonts/Blinker-Regular.ttf
          weight: 400
        - asset: assets/fonts/Blinker-Bold.ttf
          weight: 700
        - asset: assets/fonts/Blinker-Light.ttf
          weight: 100
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400


  uses-material-design: true

