// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxEmdPiuDultH7W2y5JIodYKgK7E8W5IU',
    appId: '1:10272262720:web:f3956c7269459ea67ceda5',
    messagingSenderId: '10272262720',
    projectId: 'freqfit-98e73',
    authDomain: 'freqfit-98e73.firebaseapp.com',
    storageBucket: 'freqfit-98e73.appspot.com',
    measurementId: 'G-NXRLS1NTXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCld4bXqEI1i_InzZad3xQZWLe-5p_cPZM',
    appId: '1:10272262720:android:02c15ad5d5989e127ceda5',
    messagingSenderId: '10272262720',
    projectId: 'freqfit-98e73',
    storageBucket: 'freqfit-98e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCRmidIVk-_urv7VqHHF4KE4rK8U85Jqk',
    appId: '1:10272262720:ios:275b072fc3bc8c867ceda5',
    messagingSenderId: '10272262720',
    projectId: 'freqfit-98e73',
    storageBucket: 'freqfit-98e73.appspot.com',
    iosBundleId: 'com.example.freqFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCRmidIVk-_urv7VqHHF4KE4rK8U85Jqk',
    appId: '1:10272262720:ios:6363d5cd39a6933b7ceda5',
    messagingSenderId: '10272262720',
    projectId: 'freqfit-98e73',
    storageBucket: 'freqfit-98e73.appspot.com',
    iosBundleId: 'com.example.freqFit.RunnerTests',
  );
}
